name = "JuliaScript"
uuid = "eac5aaee-ac7f-40cd-ab88-b72e0a6c4bd0"
authors = ["Stephan Sahm <stephan.sahm@jolin.io> and contributors"]
version = "1.0.0-DEV"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
